// @generated by protoc-gen-es v2.2.1 with parameter "target=ts"
// @generated from file character.proto (package Protocol, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv1";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv1";
import type { CharacterData } from "./struct_pb";
import { file_struct } from "./struct_pb";
import type { CardType } from "./enum_pb";
import { file_enum } from "./enum_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file character.proto.
 */
export const file_character: GenFile = /*@__PURE__*/
  fileDesc("Cg9jaGFyYWN0ZXIucHJvdG8SCFByb3RvY29sIjEKGUMyQl9Qb3NpdGlvblVwZGF0ZVJlcXVlc3QSCQoBeBgBIAEoARIJCgF5GAIgASgBIlUKHkIyQ19Qb3NpdGlvblVwZGF0ZU5vdGlmaWNhdGlvbhIzChJjaGFyYWN0ZXJQb3NpdGlvbnMYASADKAsyFy5Qcm90b2NvbC5DaGFyYWN0ZXJEYXRhIjoKEkMyQl9Vc2VDYXJkUmVxdWVzdBIkCghjYXJkVHlwZRgBIAEoDjISLlByb3RvY29sLkNhcmRUeXBlIiwKF0IyQ19Vc2VDYXJkTm90aWZpY2F0aW9uEhEKCWlzU3VjY2VzcxgBIAEoCGIGcHJvdG8z", [file_struct, file_enum]);

/**
 * 캐릭터 위치 동기화
 *
 * @generated from message Protocol.C2B_PositionUpdateRequest
 */
export type C2B_PositionUpdateRequest = Message<"Protocol.C2B_PositionUpdateRequest"> & {
  /**
   * @generated from field: double x = 1;
   */
  x: number;

  /**
   * @generated from field: double y = 2;
   */
  y: number;
};

/**
 * Describes the message Protocol.C2B_PositionUpdateRequest.
 * Use `create(C2B_PositionUpdateRequestSchema)` to create a new message.
 */
export const C2B_PositionUpdateRequestSchema: GenMessage<C2B_PositionUpdateRequest> = /*@__PURE__*/
  messageDesc(file_character, 0);

/**
 * 캐릭터 위치 동기화 알림
 *
 * @generated from message Protocol.B2C_PositionUpdateNotification
 */
export type B2C_PositionUpdateNotification = Message<"Protocol.B2C_PositionUpdateNotification"> & {
  /**
   * @generated from field: repeated Protocol.CharacterData characterPositions = 1;
   */
  characterPositions: CharacterData[];
};

/**
 * Describes the message Protocol.B2C_PositionUpdateNotification.
 * Use `create(B2C_PositionUpdateNotificationSchema)` to create a new message.
 */
export const B2C_PositionUpdateNotificationSchema: GenMessage<B2C_PositionUpdateNotification> = /*@__PURE__*/
  messageDesc(file_character, 1);

/**
 * 카드 사용
 *
 * @generated from message Protocol.C2B_UseCardRequest
 */
export type C2B_UseCardRequest = Message<"Protocol.C2B_UseCardRequest"> & {
  /**
   * @generated from field: Protocol.CardType cardType = 1;
   */
  cardType: CardType;
};

/**
 * Describes the message Protocol.C2B_UseCardRequest.
 * Use `create(C2B_UseCardRequestSchema)` to create a new message.
 */
export const C2B_UseCardRequestSchema: GenMessage<C2B_UseCardRequest> = /*@__PURE__*/
  messageDesc(file_character, 2);

/**
 * 카드 사용 알림
 *
 * @generated from message Protocol.B2C_UseCardNotification
 */
export type B2C_UseCardNotification = Message<"Protocol.B2C_UseCardNotification"> & {
  /**
   * @generated from field: bool isSuccess = 1;
   */
  isSuccess: boolean;
};

/**
 * Describes the message Protocol.B2C_UseCardNotification.
 * Use `create(B2C_UseCardNotificationSchema)` to create a new message.
 */
export const B2C_UseCardNotificationSchema: GenMessage<B2C_UseCardNotification> = /*@__PURE__*/
  messageDesc(file_character, 3);

