// @generated by protoc-gen-es v2.2.1 with parameter "target=ts"
// @generated from file skill.proto (package Protocol, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv1";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv1";
import type { CardType } from "./enum_pb";
import { file_enum } from "./enum_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file skill.proto.
 */
export const file_skill: GenFile = /*@__PURE__*/
  fileDesc("Cgtza2lsbC5wcm90bxIIUHJvdG9jb2wiOAoQQzJCX1NraWxsUmVxdWVzdBIkCghjYXJkVHlwZRgBIAEoDjISLlByb3RvY29sLkNhcmRUeXBlIiYKEUMyQl9Ta2lsbFJlc3BvbnNlEhEKCWlzU3VjY2VzcxgBIAEoCCJHCg9DMkJfU2tpbGxOb3RpZnkSJAoIY2FyZFR5cGUYASABKA4yEi5Qcm90b2NvbC5DYXJkVHlwZRIOCgZ1c2VySWQYAiABKAViBnByb3RvMw", [file_enum]);

/**
 * 스킬 카드 사용 요청
 *
 * @generated from message Protocol.C2B_SkillRequest
 */
export type C2B_SkillRequest = Message<"Protocol.C2B_SkillRequest"> & {
  /**
   * @generated from field: Protocol.CardType cardType = 1;
   */
  cardType: CardType;
};

/**
 * Describes the message Protocol.C2B_SkillRequest.
 * Use `create(C2B_SkillRequestSchema)` to create a new message.
 */
export const C2B_SkillRequestSchema: GenMessage<C2B_SkillRequest> = /*@__PURE__*/
  messageDesc(file_skill, 0);

/**
 * 스킬 카드 사용 응답
 *
 * @generated from message Protocol.C2B_SkillResponse
 */
export type C2B_SkillResponse = Message<"Protocol.C2B_SkillResponse"> & {
  /**
   * @generated from field: bool isSuccess = 1;
   */
  isSuccess: boolean;
};

/**
 * Describes the message Protocol.C2B_SkillResponse.
 * Use `create(C2B_SkillResponseSchema)` to create a new message.
 */
export const C2B_SkillResponseSchema: GenMessage<C2B_SkillResponse> = /*@__PURE__*/
  messageDesc(file_skill, 1);

/**
 * 스킬 카드 사용 알림
 *
 * @generated from message Protocol.C2B_SkillNotify
 */
export type C2B_SkillNotify = Message<"Protocol.C2B_SkillNotify"> & {
  /**
   * @generated from field: Protocol.CardType cardType = 1;
   */
  cardType: CardType;

  /**
   * @generated from field: int32 userId = 2;
   */
  userId: number;
};

/**
 * Describes the message Protocol.C2B_SkillNotify.
 * Use `create(C2B_SkillNotifySchema)` to create a new message.
 */
export const C2B_SkillNotifySchema: GenMessage<C2B_SkillNotify> = /*@__PURE__*/
  messageDesc(file_skill, 2);

