// @generated by protoc-gen-es v2.2.1 with parameter "target=ts"
// @generated from file enum.proto (package Protocol, syntax proto3)
/* eslint-disable */

import type { GenEnum, GenFile } from "@bufbuild/protobuf/codegenv1";
import { enumDesc, fileDesc } from "@bufbuild/protobuf/codegenv1";

/**
 * Describes the file enum.proto.
 */
export const file_enum: GenFile = /*@__PURE__*/
  fileDesc("CgplbnVtLnByb3RvEghQcm90b2NvbCozCg1Sb29tU3RhdGVUeXBlEggKBFdBSVQQABILCgdQUkVQQVJFEAESCwoHSU5BR0FNRRACKjkKCk9iamVjdFR5cGUSCQoFVE9XRVIQABIKCgZQTEFZRVIQARILCgdNT05TVEVSEAISBwoDRU5WEAMqMgoIQ2FyZFR5cGUSEAoMQVRUQUNLX1RPV0VSEAASFAoQU1RSX0FUVEFDS19UT1dFUhABKoABCg1DaGFyYWN0ZXJUeXBlEhEKDU5vbmVDaGFyYWN0ZXIQABIHCgNSZWQQARIJCgVTaGFyaxADEgoKBk1hbGFuZxAFEgoKBkZyb2dneRAHEgsKB0JvbWJNYW4QCBILCgdTbG93TWFuEAkSCAoETWFzaxAKEgwKCERpbm9zb3VyEAxiBnByb3RvMw");

/**
 * 변경 주의(클라 의존성)
 *
 * @generated from enum Protocol.RoomStateType
 */
export enum RoomStateType {
  /**
   * @generated from enum value: WAIT = 0;
   */
  WAIT = 0,

  /**
   * @generated from enum value: PREPARE = 1;
   */
  PREPARE = 1,

  /**
   * @generated from enum value: INAGAME = 2;
   */
  INAGAME = 2,
}

/**
 * Describes the enum Protocol.RoomStateType.
 */
export const RoomStateTypeSchema: GenEnum<RoomStateType> = /*@__PURE__*/
  enumDesc(file_enum, 0);

/**
 * @generated from enum Protocol.ObjectType
 */
export enum ObjectType {
  /**
   * @generated from enum value: TOWER = 0;
   */
  TOWER = 0,

  /**
   * @generated from enum value: PLAYER = 1;
   */
  PLAYER = 1,

  /**
   * @generated from enum value: MONSTER = 2;
   */
  MONSTER = 2,

  /**
   * @generated from enum value: ENV = 3;
   */
  ENV = 3,
}

/**
 * Describes the enum Protocol.ObjectType.
 */
export const ObjectTypeSchema: GenEnum<ObjectType> = /*@__PURE__*/
  enumDesc(file_enum, 1);

/**
 * @generated from enum Protocol.CardType
 */
export enum CardType {
  /**
   * @generated from enum value: ATTACK_TOWER = 0;
   */
  ATTACK_TOWER = 0,

  /**
   * 추가해야됨
   *
   * @generated from enum value: STR_ATTACK_TOWER = 1;
   */
  STR_ATTACK_TOWER = 1,
}

/**
 * Describes the enum Protocol.CardType.
 */
export const CardTypeSchema: GenEnum<CardType> = /*@__PURE__*/
  enumDesc(file_enum, 2);

/**
 * 캐릭터 타입, 변경 주의(클라 의존성)
 *
 * @generated from enum Protocol.CharacterType
 */
export enum CharacterType {
  /**
   * @generated from enum value: NoneCharacter = 0;
   */
  NoneCharacter = 0,

  /**
   * @generated from enum value: Red = 1;
   */
  Red = 1,

  /**
   * @generated from enum value: Shark = 3;
   */
  Shark = 3,

  /**
   * @generated from enum value: Malang = 5;
   */
  Malang = 5,

  /**
   * @generated from enum value: Froggy = 7;
   */
  Froggy = 7,

  /**
   * @generated from enum value: BombMan = 8;
   */
  BombMan = 8,

  /**
   * @generated from enum value: SlowMan = 9;
   */
  SlowMan = 9,

  /**
   * @generated from enum value: Mask = 10;
   */
  Mask = 10,

  /**
   * @generated from enum value: Dinosour = 12;
   */
  Dinosour = 12,
}

/**
 * Describes the enum Protocol.CharacterType.
 */
export const CharacterTypeSchema: GenEnum<CharacterType> = /*@__PURE__*/
  enumDesc(file_enum, 3);

