// @generated by protoc-gen-es v2.2.1 with parameter "target=ts"
// @generated from file init.proto (package Protocol, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv1";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv1";
import type { GamePlayerData } from "./struct_pb";
import { file_struct } from "./struct_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file init.proto.
 */
export const file_init: GenFile = /*@__PURE__*/
  fileDesc("Cgppbml0LnByb3RvEghQcm90b2NvbCIdCghMMkNfSW5pdBIRCglpc1N1Y2Nlc3MYASABKAgiLAoIQzJMX0luaXQSDgoGdXNlcklkGAEgASgJEhAKCG5pY2tuYW1lGAIgASgJIkgKCEMyQl9Jbml0EiwKCnBsYXllckRhdGEYASABKAsyGC5Qcm90b2NvbC5HYW1lUGxheWVyRGF0YRIOCgZyb29tSWQYAiABKAUiHAoIQjJMX0luaXQSEAoIc2VydmVySWQYASABKAliBnByb3RvMw", [file_struct]);

/**
 * @generated from message Protocol.L2C_Init
 */
export type L2C_Init = Message<"Protocol.L2C_Init"> & {
  /**
   * @generated from field: bool isSuccess = 1;
   */
  isSuccess: boolean;
};

/**
 * Describes the message Protocol.L2C_Init.
 * Use `create(L2C_InitSchema)` to create a new message.
 */
export const L2C_InitSchema: GenMessage<L2C_Init> = /*@__PURE__*/
  messageDesc(file_init, 0);

/**
 * 최초 패킷 구조
 *
 * @generated from message Protocol.C2L_Init
 */
export type C2L_Init = Message<"Protocol.C2L_Init"> & {
  /**
   * @generated from field: string userId = 1;
   */
  userId: string;

  /**
   * @generated from field: string nickname = 2;
   */
  nickname: string;
};

/**
 * Describes the message Protocol.C2L_Init.
 * Use `create(C2L_InitSchema)` to create a new message.
 */
export const C2L_InitSchema: GenMessage<C2L_Init> = /*@__PURE__*/
  messageDesc(file_init, 1);

/**
 * @generated from message Protocol.C2B_Init
 */
export type C2B_Init = Message<"Protocol.C2B_Init"> & {
  /**
   * @generated from field: Protocol.GamePlayerData playerData = 1;
   */
  playerData?: GamePlayerData;

  /**
   * @generated from field: int32 roomId = 2;
   */
  roomId: number;
};

/**
 * Describes the message Protocol.C2B_Init.
 * Use `create(C2B_InitSchema)` to create a new message.
 */
export const C2B_InitSchema: GenMessage<C2B_Init> = /*@__PURE__*/
  messageDesc(file_init, 2);

/**
 * @generated from message Protocol.B2L_Init
 */
export type B2L_Init = Message<"Protocol.B2L_Init"> & {
  /**
   * UUID
   *
   * @generated from field: string serverId = 1;
   */
  serverId: string;
};

/**
 * Describes the message Protocol.B2L_Init.
 * Use `create(B2L_InitSchema)` to create a new message.
 */
export const B2L_InitSchema: GenMessage<B2L_Init> = /*@__PURE__*/
  messageDesc(file_init, 3);

