// @generated by protoc-gen-es v2.2.1 with parameter "target=ts"
// @generated from file tower.proto (package Protocol, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv1";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv1";
import type { TowerData } from "./struct_pb";
import { file_struct } from "./struct_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file tower.proto.
 */
export const file_tower: GenFile = /*@__PURE__*/
  fileDesc("Cgt0b3dlci5wcm90bxIIUHJvdG9jb2wiTAoVQzJCX1Rvd2VyQnVpbGRSZXF1ZXN0EiIKBXRvd2VyGAEgASgLMhMuUHJvdG9jb2wuVG93ZXJEYXRhEg8KB293bmVySWQYAiABKAUiTwoWQjJDX1Rvd2VyQnVpbGRSZXNwb25zZRIRCglpc1N1Y2Nlc3MYASABKAgSIgoFdG93ZXIYAiABKAsyEy5Qcm90b2NvbC5Ub3dlckRhdGEiTwoYQjJDX0FkZFRvd2VyTm90aWZpY2F0aW9uEiIKBXRvd2VyGAEgASgLMhMuUHJvdG9jb2wuVG93ZXJEYXRhEg8KB293bmVySWQYAiABKAUiOwoWQjJDX1Rvd2VyQXR0YWNrUmVxdWVzdBIPCgd0b3dlcklkGAEgASgFEhAKCHRhcmdldElkGAIgASgFIlYKG0IyQ19Ub3dlckF0dGFja05vdGlmaWNhdGlvbhIRCglpc1N1Y2Nlc3MYASABKAgSDgoGZGFtYWdlGAIgASgFEhQKDHRhcmdldEhlYWx0aBgDIAEoBSIqChdDMkJfVG93ZXJEZXN0cm95UmVxdWVzdBIPCgd0b3dlcklkGAEgASgFIisKGEMyQl9Ub3dlckRlc3Ryb3lSZXNwb25zZRIPCgd0b3dlcklkGAEgASgFIi8KHEMyQl9Ub3dlckRlc3Ryb3lOb3RpZmljYXRpb24SDwoHdG93ZXJJZBgBIAEoBWIGcHJvdG8z", [file_struct]);

/**
 * 타워 생성 요청
 *
 * @generated from message Protocol.C2B_TowerBuildRequest
 */
export type C2B_TowerBuildRequest = Message<"Protocol.C2B_TowerBuildRequest"> & {
  /**
   * 타워 정보
   *
   * @generated from field: Protocol.TowerData tower = 1;
   */
  tower?: TowerData;

  /**
   * 유저 ID
   *
   * @generated from field: int32 ownerId = 2;
   */
  ownerId: number;
};

/**
 * Describes the message Protocol.C2B_TowerBuildRequest.
 * Use `create(C2B_TowerBuildRequestSchema)` to create a new message.
 */
export const C2B_TowerBuildRequestSchema: GenMessage<C2B_TowerBuildRequest> = /*@__PURE__*/
  messageDesc(file_tower, 0);

/**
 * 타워 생성 응답
 *
 * @generated from message Protocol.B2C_TowerBuildResponse
 */
export type B2C_TowerBuildResponse = Message<"Protocol.B2C_TowerBuildResponse"> & {
  /**
   * @generated from field: bool isSuccess = 1;
   */
  isSuccess: boolean;

  /**
   * 생성된 타워 정보
   *
   * @generated from field: Protocol.TowerData tower = 2;
   */
  tower?: TowerData;
};

/**
 * Describes the message Protocol.B2C_TowerBuildResponse.
 * Use `create(B2C_TowerBuildResponseSchema)` to create a new message.
 */
export const B2C_TowerBuildResponseSchema: GenMessage<B2C_TowerBuildResponse> = /*@__PURE__*/
  messageDesc(file_tower, 1);

/**
 * 타워 생성 알림
 *
 * @generated from message Protocol.B2C_AddTowerNotification
 */
export type B2C_AddTowerNotification = Message<"Protocol.B2C_AddTowerNotification"> & {
  /**
   * 생성된 타워 정보
   *
   * @generated from field: Protocol.TowerData tower = 1;
   */
  tower?: TowerData;

  /**
   * 타워 생성자 ID
   *
   * @generated from field: int32 ownerId = 2;
   */
  ownerId: number;
};

/**
 * Describes the message Protocol.B2C_AddTowerNotification.
 * Use `create(B2C_AddTowerNotificationSchema)` to create a new message.
 */
export const B2C_AddTowerNotificationSchema: GenMessage<B2C_AddTowerNotification> = /*@__PURE__*/
  messageDesc(file_tower, 2);

/**
 * 타워 공격 요청
 *
 * @generated from message Protocol.B2C_TowerAttackRequest
 */
export type B2C_TowerAttackRequest = Message<"Protocol.B2C_TowerAttackRequest"> & {
  /**
   * @generated from field: int32 towerId = 1;
   */
  towerId: number;

  /**
   * @generated from field: int32 targetId = 2;
   */
  targetId: number;
};

/**
 * Describes the message Protocol.B2C_TowerAttackRequest.
 * Use `create(B2C_TowerAttackRequestSchema)` to create a new message.
 */
export const B2C_TowerAttackRequestSchema: GenMessage<B2C_TowerAttackRequest> = /*@__PURE__*/
  messageDesc(file_tower, 3);

/**
 * @generated from message Protocol.B2C_TowerAttackNotification
 */
export type B2C_TowerAttackNotification = Message<"Protocol.B2C_TowerAttackNotification"> & {
  /**
   * @generated from field: bool isSuccess = 1;
   */
  isSuccess: boolean;

  /**
   * @generated from field: int32 damage = 2;
   */
  damage: number;

  /**
   * @generated from field: int32 targetHealth = 3;
   */
  targetHealth: number;
};

/**
 * Describes the message Protocol.B2C_TowerAttackNotification.
 * Use `create(B2C_TowerAttackNotificationSchema)` to create a new message.
 */
export const B2C_TowerAttackNotificationSchema: GenMessage<B2C_TowerAttackNotification> = /*@__PURE__*/
  messageDesc(file_tower, 4);

/**
 * @generated from message Protocol.C2B_TowerDestroyRequest
 */
export type C2B_TowerDestroyRequest = Message<"Protocol.C2B_TowerDestroyRequest"> & {
  /**
   * @generated from field: int32 towerId = 1;
   */
  towerId: number;
};

/**
 * Describes the message Protocol.C2B_TowerDestroyRequest.
 * Use `create(C2B_TowerDestroyRequestSchema)` to create a new message.
 */
export const C2B_TowerDestroyRequestSchema: GenMessage<C2B_TowerDestroyRequest> = /*@__PURE__*/
  messageDesc(file_tower, 5);

/**
 * @generated from message Protocol.C2B_TowerDestroyResponse
 */
export type C2B_TowerDestroyResponse = Message<"Protocol.C2B_TowerDestroyResponse"> & {
  /**
   * @generated from field: int32 towerId = 1;
   */
  towerId: number;
};

/**
 * Describes the message Protocol.C2B_TowerDestroyResponse.
 * Use `create(C2B_TowerDestroyResponseSchema)` to create a new message.
 */
export const C2B_TowerDestroyResponseSchema: GenMessage<C2B_TowerDestroyResponse> = /*@__PURE__*/
  messageDesc(file_tower, 6);

/**
 * @generated from message Protocol.C2B_TowerDestroyNotification
 */
export type C2B_TowerDestroyNotification = Message<"Protocol.C2B_TowerDestroyNotification"> & {
  /**
   * @generated from field: int32 towerId = 1;
   */
  towerId: number;
};

/**
 * Describes the message Protocol.C2B_TowerDestroyNotification.
 * Use `create(C2B_TowerDestroyNotificationSchema)` to create a new message.
 */
export const C2B_TowerDestroyNotificationSchema: GenMessage<C2B_TowerDestroyNotification> = /*@__PURE__*/
  messageDesc(file_tower, 7);

